# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.datatable.positive:
        class: AppBundle\Datatables\PositiveDatatable
        tags:
        - { name: sg.datatable.view }

#parameters:
#    app.score_calculator.transport: run
#
#services:
#    app.mailer:
#        class:        AppBundle\ScoreCalculator\ScoreCalculationService
#        arguments:    ['%app.score_calculator.transport%']
#    app.datagrid.builder.positive:
#         class:       AppBundle\DataGrid\PositiveDataGrid
#         arguments:  [thrace_data_grid.factory.datagrid]
#         arguments:  [translator]
#         arguments:  [router]
#         arguments:  [doctrine.orm.entity_manager]
#    app.datagrid.positive:
#        class:      Thrace\DataGridBundle\DataGrid\DataGrid
#        factory-service: app.datagrid.builder.positive
#        factory-method:  build
#        tags:
#              - {name: thrace_data_grid.datagrid, alias: positive}